<?php 
// namespace Others;


class ExploratoryTestCest
{
    public function _before(AcceptanceTester $I)
    {
    }

    // tests
    public function backendFrontendExploratory(\Step\Acceptance\AllSteps $I)
    {
    	$I->loginAsAdmin();
    	$I->click('Project Manager');
    		/*$I->waitForElementVisible('#wpbody-content', 30);
    		$I->checkError();
    			$I->see('New Project');
    			$I->seeElement('.pm-search');
    			$I->see('Active');
    			$I->see('Completed');
    			$I->see('Favourite');
    			$I->see('All');
    			$I->seeElement('#pm-project-filters');
    			$I->see('Grid View');
    			$I->see('List View');
        $I->wait(5);
        $I->click('.pm-project-column:nth-child(1) .pm-project-title > a');
            $I->waitForElementVisible('//div[@class="project-overview pm-project-overview-container"]', 30);
            $I->checkError();
                $I->seeElement('.pm-project-update-wrap');
                $I->seeElement('.header-settings-btn');
                $I->seeElement('.flaticon-text-document');
                $I->seeElement('.pm-search-field > input');
                $I->see('Discussions');
                $I->see('Task Lists');
                $I->see('Tasks');
                $I->see('Comments');
                $I->see('Files');
                $I->see('Milestones');
                $I->see('Users');
                $I->see('Last 30 days');
            $I->click('Activities');
                $I->waitForElementVisible('//div[@class="pm-activities pm-activities-container"]', 30);
                $I->checkError();
            $I->click('Discussions');
                $I->waitForElementVisible('//div[@class="pm-blank-template discussion"]', 30);
                $I->checkError();
                $I->seeElement('#pm-add-message');
            $I->click('Task Lists');
                $I->waitForElementVisible('.list-content-wrap', 30);
                $I->checkError();
                    $I->see('Add Task List');
                    $I->see('List View');
                    $I->see('Kanban');
                    $I->seeElement('.archive-page-button');
                    $I->seeElement('//a[@class="task-filter list-action-group task-filter-btn"]');
                    // $I->seeElement('//input[@placeholder="Add New Task (Character limit 200)"]');
                    $I->see('Inbox');
            $I->click('Milestones');
                $I->waitForElementVisible('//div[@class="pm-milestone pm-milestone-container"]', 30);
                $I->checkError();
                $I->see('Add Milestone');
            $I->click('Files');
                $I->waitForElementVisible('//div[@class="pm-files pm-files-container-pro"]', 30);
                $I->checkError();
                $I->see('Create a folder');
                $I->see('Upload a file');
                $I->see('Create a doc');
                $I->see('Link to Docs');
            $I->click('Gantt Chart');
                $I->waitForElementVisible('.pm-gantt-wrap', 30);
                $I->checkError();
            $I->click('Invoice');
                $I->waitForElementVisible('//table[@class="widefat pm-invoice pmi-invoices-list"]', 30);
                $I->checkError();
                $I->see('Add New');
            $I->click('//span[contains(text(),"Settings")]');
                $I->waitForElementVisible('.pm-pro-settings', 30);
                $I->checkError();
                $I->see('Capabilities');
                $I->click('Integration');
                    $I->waitForElementVisible('.wpuf-integrations', 30);
                    $I->checkError();
                $I->click('Label');
                    $I->waitForElementVisible('//div[@class="metabox-holder"]', 30);
                    $I->checkError();
                    $I->see('Create label');
                $I->click('Custom Field');
                    $I->waitForElementVisible('//div[@class="metabox-holder"]', 30);
                    $I->checkError();
                    $I->see('Add New');
    	$I->click('My Task');
    		$I->waitForElementVisible('#wedevs-project-manager', 30);
    		$I->checkError();
    			$I->see('Add New');
    			// $I->seeElement('//input[@id="mytaskSelectUser"]');
    			$I->seeElement('.form');
    			$I->click('Overview');
    				$I->waitForElementVisible('#pm-mytask-page-content', 30);
    				$I->checkError();
    					$I->see('Activity Filter');
    					$I->see('At a glance');
    					$I->see('Activities');
    					$I->see('My Calendar');
    			$I->click('Activities');
    				$I->waitForElementVisible('.mytask-activity', 30);
    				$I->checkError();
        $I->click('Categories');
            $I->waitForElementVisible('//div[@class="wrap nosubsub"]', 30);
            $I->checkError();
        $I->click('License');
            $I->waitForElementVisible('//div[@id="wedevs-project-manager"]//div[2]', 30);
            $I->checkError();
        $I->click('Calendar');
            $I->waitForElementVisible('#pm-calender-page', 30);
            $I->checkError();
            $I->seeElement('.calendar-filter-form');
        $I->click('Progress');
            $I->waitForElementVisible('//div[@class="wrap pm pm-front-end"]', 30);
            $I->checkError();
        $I->click('Reports');
            $I->waitForElementVisible('//div[@class="pm-wrap pm-front-end"]', 30);
            $I->checkError();
            $I->see('Advanced Report');
            $I->see('Overdue Tasks');
            $I->see('Complete Task');
            $I->see('User Activities');
            $I->see('Task by Milestone');
            $I->see('Unassigned Task');
            $I->see('Summary');
        $I->click('Modules');
            $I->waitForElementVisible('//div[@class="pm-wrap module-list-area"]', 30);
            $I->checkError();
            $I->see('KanBan Board');
            $I->see('Sub Task');
            $I->see('Custom Fields');
            $I->see('WooCommerce Order');
            $I->see('Recurring Task');
            $I->see('Gantt Chart');
            $I->see('BuddyPress Integration');
            $I->see('Time Tracker');
            $I->see('Invoice stripe payment gateway');
            $I->see('Project Invoice');*/
        $I->click('Settings');
            $I->waitForElementVisible('.Settings-page-wrapper', 30);
            $I->checkError();
        $I->click('E-Mail Settings');
            $I->waitForElementVisible('.metabox-holder', 30);
            $I->checkError();
        $I->click('Pusher');
            $I->waitForElementVisible('.metabox-holder', 30);
            $I->checkError();
        $I->click('Invoice');
            $I->waitForElementVisible('#pm_invoice', 30);
            $I->checkError();
        $I->click('//a[contains(@href, "#/settings/pages")]');
            $I->waitForElementVisible('.settingswrapper', 30);
            $I->checkError();
        $I->click('Tools');
            $I->waitForElementVisible('.wpuf-integration', 30);
            $I->checkError();
            $I->seeElement('.wpuf-integration');
        
        // Frontend exploratory testing
        $I->amOnPage('/pm/#/projects/active');
        $I->waitForElementVisible('//div[@id="wedevs-project-manager"]', 30);
            $I->checkError();
             $I->see('New Project');
             $I->seeElement('.pm-search');//div[@class='pm-form-has-addon pm-project-search']
             $I->see('Active');
             $I->see('Completed');
             $I->see('Favourite');
             $I->see('All');
             $I->seeElement('#pm-project-filters');
             $I->see('Grid View');
             $I->see('List View');
        $I->click('.pm-project-column:nth-child(1) .pm-project-title > a');
            $I->waitForElementVisible('//div[@class="project-overview pm-project-overview-container"]', 30);
            $I->checkError();
                $I->seeElement('.pm-project-update-wrap');
                $I->seeElement('.header-settings-btn');
                $I->seeElement('.flaticon-text-document');
                $I->seeElement('.pm-search-field > input');
                $I->see('Discussions');
                $I->see('Task Lists');
                $I->see('Tasks');
                $I->see('Comments');
                $I->see('Files');
                $I->see('Milestones');
                $I->see('Users');
                $I->see('Last 30 days');
                    $I->click('Activities');
                $I->waitForElementVisible('//div[@class="pm-activities pm-activities-container"]', 30);
                $I->checkError();
            $I->click('Discussions');
                $I->waitForElementVisible('//div[@class="pm-blank-template discussion"]', 30);
                $I->checkError();
                $I->seeElement('#pm-add-message');
            $I->click('Task Lists');
                $I->waitForElementVisible('.list-content-wrap', 30);
                $I->checkError();
                    $I->see('Add Task List');
                    $I->see('List View');
                    $I->see('Kanban');
                    $I->seeElement('.archive-page-button');
                    $I->seeElement('//a[@class="task-filter list-action-group task-filter-btn"]');
                    // $I->seeElement('//input[@placeholder="Add New Task (Character limit 200)"]');
                    $I->see('Inbox');
            $I->click('Milestones');
                $I->waitForElementVisible('//div[@class="pm-milestone pm-milestone-container"]', 30);
                $I->checkError();
                $I->see('Add Milestone');
            $I->click('Files');
                $I->waitForElementVisible('//div[@class="pm-files pm-files-container-pro"]', 30);
                $I->checkError();
                $I->see('Create a folder');
                $I->see('Upload a file');
                $I->see('Create a doc');
                $I->see('Link to Docs');
            $I->click('Gantt Chart');
                $I->waitForElementVisible('.pm-gantt-wrap', 30);
                $I->checkError();
            $I->click('Invoice');
                $I->waitForElementVisible('//table[@class="widefat pm-invoice pmi-invoices-list"]', 30);
                $I->checkError();
                // $I->see('Add New');
            $I->click('//span[contains(text(),"Settings")]');
                $I->waitForElementVisible('.pm-pro-settings', 30);
                $I->checkError();
                $I->see('Capabilities');
                $I->click('Integration');
                    $I->waitForElementVisible('.wpuf-integrations', 30);
                    $I->checkError();
                $I->click('Label');
                    $I->waitForElementVisible('//div[@class="metabox-holder"]', 30);
                    $I->checkError();
                    $I->see('Create label');
                $I->click('Custom Field');
                    $I->waitForElementVisible('//div[@class="metabox-holder"]', 30);
                    $I->checkError();
                    $I->see('Add New');
         $I->click('Categories');
            $I->waitForElementVisible('//div[@class="wrap nosubsub"]', 30);
            $I->checkError();
        $I->click('My tasks');
            $I->waitForElementVisible('#wedevs-project-manager', 30);
            $I->checkError();
                $I->see('Add New');
                // $I->seeElement('//input[@id="mytaskSelectUser"]');
                $I->seeElement('.form');
                $I->click('Overview');
                    $I->waitForElementVisible('#pm-mytask-page-content', 30);
                    $I->checkError();
                        $I->see('Activity Filter');
                        $I->see('At a glance');
                        $I->see('Activities');
                        $I->see('My Calendar');
                $I->click('Activities');
                    $I->waitForElementVisible('.mytask-activity', 30);
                    $I->checkError();
        $I->click('Calendar');
            $I->waitForElementVisible('#pm-calender-page', 30);
            $I->checkError();
            $I->seeElement('.calendar-filter-form');
        $I->click('Reports');
            $I->waitForElementVisible('//div[@class="pm-wrap pm-front-end"]', 30);
            $I->checkError();
            $I->see('Advanced Report');
            $I->see('Overdue Tasks');
            $I->see('Complete Task');
            $I->see('User Activities');
            $I->see('Task by Milestone');
            $I->see('Unassigned Task');
            $I->see('Summary');
        $I->click('Progress');
            $I->waitForElementVisible('//div[@class="wrap pm pm-front-end"]', 30);
            $I->checkError();
        $I->click('Modules');
            $I->waitForElementVisible('//div[@class="pm-wrap module-list-area"]', 30);
            $I->checkError();
            $I->see('KanBan Board');
            $I->see('Sub Task');
            $I->see('Custom Fields');
            $I->see('WooCommerce Order');
            $I->see('Recurring Task');
            $I->see('Gantt Chart');
            $I->see('BuddyPress Integration');
            $I->see('Time Tracker');
            $I->see('Invoice stripe payment gateway');
            $I->see('Project Invoice');
        $I->amOnPage('/wp-admin/post.php?post=5&action=edit');
            $I->waitForElementVisible('//div[@class="edit-post-visual-editor editor-styles-wrapper"]', 30);
            $I->checkError();
        $I->amOnPage('/wp-admin/post.php?post=6&action=edit');
            $I->waitForElementVisible('//div[@class="edit-post-visual-editor editor-styles-wrapper"]', 30);
            $I->checkError();


    			


    }
}
